### ISSUE TITLE
Hide traceback for network issues

### ISSUE THREAD

**Issue by rEnr3n** [lilydjwg/nvchecker#108]
Please replace the traceback with something more compact.

```
$ nvchecker --tries 9 ~/source.ini
[I 04-28 11:38:31.002 core:201] nextcloud: updated from 15.0.7-1 to 16.0.0-1
[I 04-28 11:38:31.204 core:201] nginx-mainline-mod-dav-ext: updated from 3.0.0-4 to 3.0.0-5
[W 04-28 11:38:49.079 core:163] nginx-mainline: failed, retrying
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/nvchecker/core.py", line 158, in worker
        name, conf, keyman=self.keymanager)
      File "/usr/lib/python3.7/site-packages/nvchecker/get_version.py", line 90, in get_version
        version = await func(name, conf, **kwargs)
      File "/usr/lib/python3.7/site-packages/nvchecker/source/archpkg.py", line 17, in get_version
        async with session.get(URL, params={"name": pkg}) as res:
      File "/usr/lib/python3.7/site-packages/nvchecker/source/tornado_httpclient.py", line 62, in __aenter__
        return await to_asyncio_future(client.fetch(self.req))
    tornado.curl_httpclient.CurlError: HTTP 599: Connection timed out after 20000 milliseconds
[W 04-28 11:38:49.100 core:163] php: failed, retrying
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/nvchecker/core.py", line 158, in worker
        name, conf, keyman=self.keymanager)
      File "/usr/lib/python3.7/site-packages/nvchecker/get_version.py", line 90, in get_version
        version = await func(name, conf, **kwargs)
      File "/usr/lib/python3.7/site-packages/nvchecker/source/archpkg.py", line 17, in get_version
        async with session.get(URL, params={"name": pkg}) as res:
      File "/usr/lib/python3.7/site-packages/nvchecker/source/tornado_httpclient.py", line 62, in __aenter__
        return await to_asyncio_future(client.fetch(self.req))
    tornado.curl_httpclient.CurlError: HTTP 599: Connection timed out after 20016 milliseconds
[W 04-28 11:38:49.103 core:163] postgresql-old-upgrade: failed, retrying
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/nvchecker/core.py", line 158, in worker
        name, conf, keyman=self.keymanager)
      File "/usr/lib/python3.7/site-packages/nvchecker/get_version.py", line 90, in get_version
        version = await func(name, conf, **kwargs)
      File "/usr/lib/python3.7/site-packages/nvchecker/source/archpkg.py", line 17, in get_version
        async with session.get(URL, params={"name": pkg}) as res:
      File "/usr/lib/python3.7/site-packages/nvchecker/source/tornado_httpclient.py", line 62, in __aenter__
        return await to_asyncio_future(client.fetch(self.req))
    tornado.curl_httpclient.CurlError: HTTP 599: Connection timed out after 20012 milliseconds
[I 04-28 11:38:49.486 core:201] nginx-mainline: updated from 1.15.11-1 to 1.15.12-1
```

**Comment by lilydjwg** [comment]
This have been implemented in master. Could you give it a try and report any missed errors where a traceback is not useful?
