### ISSUE TITLE
AsyncHTTPClient get 599 error when runnning in cron

### ISSUE THREAD

**Issue by amazingfate** [lilydjwg/nvchecker#12]
here is the cron command:
```source $HOME/.bash_profile && /usr/local/bin/nvchecker $HOME/nvchecker/nvchecker.ini > $HOME/nvchecker/update.log 2>&1```
only in cron it runs with the following error:
```
[E 09-14 10:30:21.776 ioloop:612] Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x7f173141dae8>, HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://www.archlinux.org/packages/search/json/?name=warsow',error=CurlError('HTTP 599: Operation timed out after 0 milliseconds with 0 out of 0 bytes received',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f173141e390>,request_time=20.00719165802002,time_info={}))
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 592, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 343, in wrapped
        raise_exc_info(exc)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 355, in _handle_exception
        if tail.exit(*exc):
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 186, in exit
        return self.exception_handler(type, value, traceback)
      File "/usr/local/lib/python3.4/dist-packages/nvchecker-0.4dev-py3.4.egg/nvchecker/core.py", line 98, in _handle_exception
        raise value.with_traceback(traceback)
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/nvchecker-0.4dev-py3.4.egg/nvchecker/source/archpkg.py", line 17, in _pkg_done
        raise res.error
    tornado.curl_httpclient.CurlError: HTTP 599: Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```

**Comment by lilydjwg** [comment]
For some reason it timed out. Would you paste what `env` outputs in and outside cron?

**Comment by amazingfate** [comment]
curl works well in cron

**Comment by amazingfate** [comment]
It should be the problem of my poor network, this morning I used nvchecker outside the cron but still get 599 error.
