### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by braam** [lilydjwg/nvchecker#190]
I can't connect to websites with a self-signed-certificate, following error popups up. How can I fix this? 
```
[E 06-22 20:59:13.160 core:326] myPortal@Work-Win: unexpected error happened error=HTTP 599: server certificate verification failed. CAfile: none CRLfile: none
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/nvchecker/util.py", line 233, in run_one
        keymanager = self.keymanager,
      File "/usr/local/lib/python3.7/dist-packages/nvchecker_source/regex.py", line 11, in get_version
        return await cache.get(key, get_version_impl)
      File "/usr/local/lib/python3.7/dist-packages/nvchecker/util.py", line 177, in get
        r = await fu
      File "/usr/local/lib/python3.7/dist-packages/nvchecker_source/regex.py", line 23, in get_version_impl
        res = await session.get(conf['url'])
      File "/usr/local/lib/python3.7/dist-packages/nvchecker/httpclient/base.py", line 50, in get
        method='GET', *args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/nvchecker/httpclient/base.py", line 81, in request
        proxy = p or None,
      File "/usr/local/lib/python3.7/dist-packages/nvchecker/httpclient/tornado_httpclient.py", line 78, in request_impl
        r, raise_error=False)
    tornado.curl_httpclient.CurlError: HTTP 599: server certificate verification failed. CAfile: none CRLfile: none

```

**Comment by lilydjwg** [comment]
An option `verify_cert` has been added and you can specify `verify_cert = false` now.

**Comment by braam** [comment]
Thanks for quick fix, was exactly what I had in mind :+1:
