### ISSUE TITLE
Missing configuration options result in unclear, uncaught error messages

### ISSUE THREAD

**Issue by C0rn3j** [lilydjwg/nvchecker#279]
It would be nice if these config issues were caught with a human readable error thrown back, the current error with this wrong config [made me think](https://gitlab.archlinux.org/archlinux/devtools/-/issues/248#note_220965) downstream `pkgctl` wasn't using the config correctly.

```toml
[vtracer]
source = "github"
git = "https://github.com/visioncortex/vtracer.git"
```

```python
% nvchecker -c nvchecker.toml
[E 11-04 20:37:09.918 core:369] vtracer: unexpected error happened error=KeyError('github')
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/nvchecker/util.py", line 311, in run_one
        version = await self.func(
                  ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/nvchecker_source/github.py", line 39, in get_version
        return await get_version_real(name, conf, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/nvchecker_source/github.py", line 158, in get_version_real
        repo = conf['github']
               ~~~~^^^^^^^^^^
    KeyError: 'github'
[E 11-04 20:37:09.919 core:447] vtracer: no-result error="'github'"
```

https://github.com/lilydjwg/nvchecker/blob/28f1ab51443d88a7ab4f52feaf71aaa359f5fe9e/nvchecker_source/github.py#L164

**Comment by lilydjwg** [comment]
Yes, the latter error message is quite confusing. I'm changing `str(e)` to `repr(e)` as some builtin Python exceptions has such messages.

A better way to handle this is to validate the config file via a schema, but that's a lot of work to do...
