### ISSUE TITLE
tornado版本的aur链接访问出错

### ISSUE THREAD

**Issue by petronny** [lilydjwg/nvchecker#41]
如题，运行会出下述错误
```
[E 08-24 21:10:14.158 ioloop:633] Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x7f947bdc9f28>, HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=bazel',error=OSError(97, 'Address
family not supported by protocol'),headers=<tornado.httputil.HTTPHeaders object at 0x7f9478beaa90>,reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f947bddc940>,request_time=0.3073916435241699,time_info={}))
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/tornado/ioloop.py", line 604, in _run_callback
        ret = callback()
      File "/usr/lib/python3.5/site-packages/tornado/stack_context.py", line 343, in wrapped
        raise_exc_info(exc)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib/python3.5/site-packages/tornado/stack_context.py", line 355, in _handle_exception
        if tail.exit(*exc):
      File "/usr/lib/python3.5/site-packages/tornado/stack_context.py", line 186, in exit
        return self.exception_handler(type, value, traceback)
      File "/usr/lib/python3.5/site-packages/nvchecker/core.py", line 100, in _handle_exception
        raise value.with_traceback(traceback)
      File "/usr/lib/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/nvchecker/source/aur.py", line 21, in _aur_done
        raise res.error
      File "/usr/lib/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/tornado/tcpclient.py", line 130, in on_timeout
        self.try_connect(iter(self.secondary_addrs))
      File "/usr/lib/python3.5/site-packages/tornado/tcpclient.py", line 96, in try_connect
        future = self.connect(af, addr)
      File "/usr/lib/python3.5/site-packages/tornado/tcpclient.py", line 180, in _create_stream
        stream = IOStream(socket.socket(af),
      File "/usr/lib/python3.5/socket.py", line 134, in __init__
        _socket.socket.__init__(self, family, type, proto, fileno)
    OSError: [Errno 97] Address family not supported by protocol
```
装了pycurl后一切正常，但是pycurl是optional dependency啊

**Comment by lilydjwg** [comment]
试试以下代码会报错吗？

```
#!/usr/bin/env python3

from tornado import ioloop, gen
from tornado.httpclient import AsyncHTTPClient

@gen.coroutine
def main():
  res = yield AsyncHTTPClient().fetch('https://aur.archlinux.org/')
  print('ok')

if __name__ == '__main__':
  loop = ioloop.IOLoop.current()
  loop.run_sync(main)
```

你的系统关闭了 IPv6 支持吗？

**Comment by petronny** [comment]
会出错
的确关闭了IPv6支持...

**Comment by lilydjwg** [comment]
那你为什么会解析到 IPv6 地址？

**Comment by petronny** [comment]
我直接从kernel 启动参数加了ipv6.disable=1
按理说不会啊。。

**Comment by lilydjwg** [comment]
`getaddrinfo` 还真会……

**Comment by petronny** [comment]
我试了试nslookup和dig都能查到
不过获取到应该没问题吧，就是查询AAAA记录而已
问题是为什么已知系统ipv6没了还是会优先ipv6地址，其他的应用都会用ipv4的

**Comment by petronny** [comment]
我去tornado发issue好了

**Comment by lilydjwg** [comment]
我正在发……

**Comment by petronny** [comment]
_(:з」∠)_

**Comment by lilydjwg** [comment]
我记得 glibc 有探测是否支持 IPv6 协议的。大概那个是在 gethostbyname 之类别的函数里用的？

**Comment by petronny** [comment]
res = yield AsyncHTTPClient().fetch('https://aur.archlinux.org/',allow_ipv6=False)
改成这样以后能用

**Comment by lilydjwg** [comment]
@petronny 你试试 https://github.com/tornadoweb/tornado/pull/1821 看？
