### ISSUE TITLE
Proxy and pycurl

### ISSUE THREAD

**Issue by sylvainmouquet** [lilydjwg/nvchecker#63]
Hello,

When i add the pycurl dependency, i have this error : 

```
[E 11-22 09:16:33.365 core:129] unexpected error happened with influxdb
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/nvchecker/core.py", line 125, in future_done
        version = fu.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/usr/local/lib/python3.5/dist-packages/nvchecker/get_version.py", line 19, in get_version
        return await func(name, conf)
      File "/usr/local/lib/python3.5/dist-packages/nvchecker/source/github.py", line 36, in get_version
        async with session.get(url, headers=headers, **kwargs) as res:
      File "/usr/local/lib/python3.5/dist-packages/nvchecker/source/tornado_httpclient.py", line 54, in __aenter__
        return await to_asyncio_future(client.fetch(self.req))
      File "/usr/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/curl_httpclient.py", line 214, in _process_queue
        curl.info["headers"])
      File "/usr/local/lib/python3.5/dist-packages/tornado/curl_httpclient.py", line 474, in _curl_setup_request
        request.prepare_curl_callback(curl)
      File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/nvchecker/source/tornado_httpclient.py", line 24, in try_use_http2
        curl.setopt(pycurl.HTTP_VERSION, 4)
    pycurl.error: (1, '')
```

If i disable the line `curl.setopt(pycurl.HTTP_VERSION, 4)` it works

**Comment by lilydjwg** [comment]
Which version of curl / libcurl are you using?

**Comment by lilydjwg** [comment]
This should have been fixed anyway.
